<?php
/**
 * @file
 * password_expire.module
 * 
 */

define('PASSWORD_OK', 0);
define('PASSWORD_NEEDS_RENEWAL', 1);
define('PASSWORD_EXPIRED', 2);
define('PASSWORD_SAME', 3);

/**
* Display help and module information
* 
*/
function password_expire_help($path, $arg) {
  switch ($path) {
    case "admin/help#password_expire":
      return t("<p>Allows administrators to set an expiry date on passwords. Users that do not renew their passwords within the given time will have their passwords reset to a randomly generated one.</p><p>You can schedule warning messages notifying users when their password is close to expiry. If you have the actions module enabled, then you can also schedule emails to be sent. Both messages and emails can use (but do not require) the <a href='http://drupal.org/project/token'>token</a> module, and provides tokens such as [password_expire:pass-expire-days-left] and [password_expire:pass-expire-date].</p><p>Note: In order for password expiry to work properly, cron must be scheduled regularly.</p>");
  } 
}

/**
 * Implements hook_menu()
 * 
 */
function password_expire_menu() {
  $items = array();
  
  $items['password/change'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('password_expire_new_password_form'),
    'access callback' => 'user_is_logged_in'
  );

  $items['password/success'] = array(
    'page callback' => '_password_expire_password_success',
    'access callback' => 'user_is_logged_in'
  );

  $items['password/error'] = array(
    'page callback' => '_password_expire_password_error',
    'access callback' => 'user_is_logged_in'
  );

  $items['admin/config/people/accounts/password_expire'] = array(
    'title' => 'Password Expire',
    'description' => 'Configuration for password expire',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('password_expire_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'password_expire.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_token_info()
 * Define tokens this module contributes
 *
 * @param string $type
 * @example 
 * 	token: [pass-expire-days-left]	- $info['tokens']['password_expire']['pass-expire-days-left']
 * 	
 * @return array
 */
function password_expire_token_info() {
  $info = array();
  $info['types']['password_expire'] = array(
    'name' => t('Password Expire Tokens'),
    'description' => t('Tokens for password expire.'),
  );

  $info['tokens']['password_expire']['pass-expire-days-left'] = array('name' => t('Password expiry days left'), 'description' => t('Days left until user\'s password will expire'));
  $info['tokens']['password_expire']['pass-expire-yyyy']      = array('name' => t('Password expiry year (four digits)'), 'description' => t('The year the password will expire (four digits)'));
  $info['tokens']['password_expire']['pass-expire-yy']        = array('name' => t('Password expiry year (two digits)'), 'description' => t('The year the password will expire (two digits)'));
  $info['tokens']['password_expire']['pass-expire-month']     = array('name' => t('Password expiry month (full word)'), 'description' => t('The month the password will expire (ex. January)'));
  $info['tokens']['password_expire']['pass-expire-mon']       = array('name' => t('Password expiry month (abbreviated)'), 'description' => t('The abbreviated month the password will expire (ex. Jan)'));
  $info['tokens']['password_expire']['pass-expire-mm']        = array('name' => t('Password expiry month (two digit, zero padded)'), 'description' => t('The month the password will expire (ex. 01)'));
  $info['tokens']['password_expire']['pass-expire-m']         = array('name' => t('Password expiry month (one or two digit)'), 'description' => t('The month the password will expire (ex. 1)'));
  $info['tokens']['password_expire']['pass-expire-ww']        = array('name' => t('Password expiry week (two digits)'), 'description' => t('The week number the password will expire (ex. 52)'));
  $info['tokens']['password_expire']['pass-expire-date']      = array('name' => t('Password expiry date (full date)'), 'description' => t('The date the password will expire (ex. '.date('Y-m-d').')'));
  $info['tokens']['password_expire']['pass-expire-day']       = array('name' => t('Password expiry day (full word)'), 'description' => t('The day the password will expire (ex. Monday)'));
  $info['tokens']['password_expire']['pass-expire-ddd']       = array('name' => t('Password expiry day (abbreviation)'), 'description' => t('The abbreviated day the password will expire (ex. Mon)'));
  $info['tokens']['password_expire']['pass-expire-dd']        = array('name' => t('Password expiry day (two digits)'), 'description' => t('The day the password will expire (ex. 01)'));
  $info['tokens']['password_expire']['pass-expire-d']         = array('name' => t('Password expiry day (one or two digits)'), 'description' => t('The day the password will expire (ex. 1)'));

  return $info;
}

/**
 * Implements hook_tokens()
 * Define tokens values this module contributes
 *
 * @param string $type
 * @param object $object
 */
function password_expire_tokens($type, $tokens, array $data = array(), array $options = array()) {
  global $user;

  if ($type == 'password_expire') {
    $expiry_date = db_query('SELECT timestamp FROM {password_expire} WHERE uid = :uid', array(':uid' => $user->uid))->fetchField();

    $days_left = ceil(($expiry_date - time()) / 86400);

    // Adjust expiry date for user timezone settings
    if (variable_get('configurable_timezones', 1) && $user->uid && strlen($user->timezone)) {
      $timezone = $user->timezone;
    } else {
      $timezone = variable_get('date_default_timezone', 0);
    }
    $expiry_date += $timezone;

    // set tokens						
    $tokens = array();
    $tokens['password_expire']['pass-expire-days-left']  = $days_left;
    $tokens['password_expire']['pass-expire-yyyy']       = date('Y', $expiry_date);
    $tokens['password_expire']['pass-expire-yy']         = date('y', $expiry_date);
    $tokens['password_expire']['pass-expire-month']      = date('F', $expiry_date);
    $tokens['password_expire']['pass-expire-mon']        = date('M', $expiry_date);
    $tokens['password_expire']['pass-expire-mm']         = date('m', $expiry_date);
    $tokens['password_expire']['pass-expire-m']          = date('n', $expiry_date);
    $tokens['password_expire']['pass-expire-ww']         = date('W', $expiry_date);
    $tokens['password_expire']['pass-expire-date']       = date('Y-m-d', $expiry_date);
    $tokens['password_expire']['pass-expire-day']        = date('l', $expiry_date);
    $tokens['password_expire']['pass-expire-ddd']        = date('D', $expiry_date);
    $tokens['password_expire']['pass-expire-dd']         = date('d', $expiry_date);
    $tokens['password_expire']['pass-expire-d']          = date('j', $expiry_date);

    return $tokens;
  }
}

function _password_expire_token_array() {
  global $user;
  global $base_root;
  $expiry_date = db_query('SELECT timestamp FROM {password_expire} WHERE uid = :uid', array(':uid' => $user->uid))->fetchField();
  $days_left = ceil(($expiry_date - time()) / 86400);
  
  // Adjust expiry date for user timezone settings
  if (variable_get('configurable_timezones', 1) && $user->uid && strlen($user->timezone)) {
    $timezone = $user->timezone;
  } else {
    $timezone = variable_get('date_default_timezone', 0);
  }
  $expiry_date += $timezone;

  $tokens = array(
    '[site:url]'                              => $base_root,
    '[password_expire:pass-expire-days-left]' => $days_left,
    '[password_expire:pass-expire-yyyy]'      => date('Y', $expiry_date),
    '[password_expire:pass-expire-yy]'        => date('y', $expiry_date),
    '[password_expire:pass-expire-month]'     => date('F', $expiry_date),
    '[password_expire:pass-expire-mon]'       => date('M', $expiry_date),
    '[password_expire:pass-expire-mm]'        => date('m', $expiry_date),
    '[password_expire:pass-expire-m]'         => date('n', $expiry_date),
    '[password_expire:pass-expire-ww]'        => date('W', $expiry_date),
    '[password_expire:pass-expire-date]'      => date('Y-m-d', $expiry_date),
    '[password_expire:pass-expire-day]'       => date('l', $expiry_date),
    '[password_expire:pass-expire-ddd]'       => date('D', $expiry_date), 
    '[password_expire:pass-expire-dd]'        => date('d', $expiry_date),
    '[password_expire:pass-expire-d]'         => date('j', $expiry_date),
  );

  return $tokens;
}
/**
 * Implements hook_hook_info()
 *
 */
function password_expire_hook_info() {
  return array(
    'password_expire' => array(
      'password_expire' => array(
        'warning' => array(
          'runs when' => t('When a users password is due to expire soon.'),
        ),
        'expire' => array(
          'runs when' => t('When a users password has expired.'),
        ),        
      ),
    ),
  );
}

/**
 * Implements hook_mail_edit_token_types()
 *
 */
function password_expire_mail_edit_token_types($mailkey) {
  return array('password_expire');
}

/**
 * Implements hook_action_info_alter()
 * 
 */
function password_expire_action_info_alter(&$info) {
  foreach ($info as $type => $data) {
    // Allow system and user actions
    if (stripos($type, "user_") === 0 || stripos($type, "system_") === 0) {
      if (isset($info[$type]['hooks']['password_expire'])) {
        array_merge($info[$type]['hooks']['password_expire'], array('warning', 'expire'));
      } else {
        $info[$type]['hooks']['password_expire'] = array('warning', 'expire');
      }
    }
  }

  // Add token_actions
  if (isset($info['token_actions_send_email_action'])) {
    if (isset($info['token_actions_send_email_action']['hooks']['password_expire'])) {
      array_merge($info['token_actions_send_email_action']['hooks']['password_expire'], array('warning', 'expire'));
    } else {
      $info['token_actions_send_email_action']['hooks']['password_expire'] = array('warning', 'expire');
    }
  }
}

/**
* Function to check whether a password is expired or not
* 
* @param string $uid - UID of the user
* @return int PASSWORD_OK, PASSWORD_NEEDS_RENEWAL, PASSWORD_EXPIRED
* 
*/
function _password_expire_is_expired($uid) {
  $q_exp = db_query('SELECT state FROM {password_expire} WHERE uid = :uid', array(':uid' => $uid))->fetchField();
  return $q_exp;
}

/**
 * Function to show expiry message to user
 * 
 * @param string $uid - UID of the user
 * @param string $type - Type of message, 1=expired message, 2=password warning
 * 
 */
function _password_expire_msg_user($uid, $type) {
  switch ($type) {
    case PASSWORD_NEEDS_RENEWAL:
      $msg = variable_get('password_expire_warning_message');
      //Prevent displaying the message twice
      unset($_SESSION['messages']);
      if ($msg == '') {
        $msg = 'Your password will expire soon!';
      }
      drupal_set_message(t($msg, _password_expire_token_array()), 'warning', FALSE);
      break;
      
    case PASSWORD_EXPIRED:
      $msg = variable_get('password_expire_expired_message');
      //Prevent displaying the message twice
      unset($_SESSION['messages']);
      if ($msg == '') {
        $msg = 'Your password is expired. Please change your password. Be sure to use a different password as before.';
      }
      drupal_set_message(t($msg, _password_expire_token_array()), 'error', FALSE);
      break;
      
  }
}

/**
 * Implements hook_user_login()
 *
 */
function password_expire_user_login(&$edit, $account) {
  // PASSWORD_EXPIRED is handled via hook_init(), so when a user clicks on
  // another link he/she will always be redirected to the password change form
  // To prevent too many checks, the password renewal check will only take place when the user logs in
  if (_password_expire_is_expired($account->uid) == PASSWORD_NEEDS_RENEWAL) {
    _password_expire_msg_user($account->uid, PASSWORD_NEEDS_RENEWAL);
  }
}

/**
 * Implements hook_init()
 *
 * To redirect user if page is loading and password is expired
 */
function password_expire_init(){
  if (_password_expire_page_is_overlayed()) {
    return FALSE;
  }

  global $user;
  $expired = db_query('SELECT p.timestamp, p.state FROM {password_expire} p WHERE p.uid = :uid LIMIT 1', array(':uid' => $user->uid))->fetchObject();

  if (user_is_logged_in() && _password_expire_is_expired($user->uid) == PASSWORD_EXPIRED) {
    //Redirect to change password, but prevent loop when user tries to logout
    if ($_GET['q'] != 'user/logout') {
      admin_menu_suppress(TRUE);
      _password_expire_msg_user($user->uid, PASSWORD_EXPIRED);
      $_GET['q'] = 'password/change';
    }
  }
}

/**
 * Implements hook_user_delete()
 *
 * To remove the user entry from password_expire
 */
function password_expire_user_delete($account) {
  //Remove entry from password_expire table
  db_delete('password_expire')
    ->condition('uid', $account->uid)
    ->execute();
}

/**
 * Implements hook_user_presave()
 *
 * To renew the expiry date of the user password
 */
function password_expire_user_presave(&$edit, $account, $category) {
  if (isset($account->is_new) && $account->is_new) {
    return;
  }

  if (!empty($edit['pass']) && $account->pass != $edit['pass']) {
    //If password changed, renew expiry date
    _password_expire_renew_expirydate($account->uid);
  }
}

/**
 * Implements hook_user_insert()
 *
 * To set the expiry date of the user password
 */
function password_expire_user_insert(&$edit, $account, $category) {
  if (isset($account->is_new) && $account->is_new == TRUE) {
    //If password changed, renew expiry date
    _password_expire_renew_expirydate($account->uid);
  }
}

/**
 * Implements hook_cron()
 * 
 * Checks for soon to expire passwords and expired passwords
 */
function password_expire_cron() {
  //Handle values that are different than normally expected to prevent that users in potention can get warning message for a long period 
  _password_expire_handle_incorrectvalues();

  //Handle soon to expire passwords
  _password_expire_handle_warnings();

  //Handle expired passwords
  _password_expire_handle_expiry();

  //Handle new users
  _password_expire_handle_newusers();	
}

/**
 * Trigger actions for users with an incorrect expiry state
 * 
 * For example when a user has a PASSWORD_NEEDS_RENEWAL state while the timestamp is more then the warning period
 * In normal circumstances this should not happen, but if for some reason the database is modified to a timestamp in the future while the state is still at PASSWORD_NEEDS_RENEWAL,
 * a user could get warning messages for lifetime. This function will prevent this to happen.
 *  
 */
function _password_expire_handle_incorrectvalues() {
  $now = time();
  $expire_period = strtotime(variable_get('password_expire_length'));
  $warning_threshold = strtotime(variable_get('password_expire_warning'));

  //Renew expiry date of passwords that have an expired state and threshold after now
  if (!empty($now)) {
    $pass_expire3 = db_update('password_expire')
      ->fields(array(
        'state' => PASSWORD_EXPIRED,
        'timestamp' => $now,
      ))
      ->condition(db_and()->condition('state', PASSWORD_EXPIRED, '=')->condition('timestamp', $now, '>'))
      ->execute();
  }

  //Renew expiry date of passwords that have an expiration later then the maximum expiry length
  if (!empty($expire_period)) {
    $pass_expire1 = db_update('password_expire')
      ->fields(array(
        'state' => PASSWORD_OK,
        'timestamp' => $expire_period,
      ))
      ->condition('timestamp', $expire_period, '>')
      ->execute();
  }

  //Renew expiry date of passwords that have an renewal state and threshold behind warning period
  //This could happen if a user was in his warning period and the warning period was changed in the configuration
  if (!empty($warning_threshold)) {
    $pass_expire2 = db_update('password_expire')
      ->fields(array(
        'state' => PASSWORD_NEEDS_RENEWAL,
        'timestamp' => $warning_threshold,
      ))
      ->condition(db_and()->condition('state', PASSWORD_NEEDS_RENEWAL, '=')->condition('timestamp', $warning_threshold, '>'))
      ->execute();
  }
}

/**
 * Trigger actions for users whos passwords are about to expire
 * 
 */
function _password_expire_handle_warnings() {
  $now = time();
  $warning_threshold = strtotime(variable_get('password_expire_warning'));
  if (!empty($warning_threshold)) {
    //Password needs renewal where field timestamp > $threshold
    $pass_warning = db_update('password_expire')
      ->fields(array(
        'state' => PASSWORD_NEEDS_RENEWAL,
      ))
      ->condition(db_and()->condition('timestamp', $now, '>=')->condition('timestamp', $warning_threshold, '<'))
      ->execute();
  }
}

/**
 * Trigger actions for users whos passwords have expired
 * 
 * @todo what to do with passwords that are expired...
 * 		 - Should the user be able to login and create a new password on first login
 * 			This is a potential risk, because if a user does not login for 2 years,
 * 			the password remains the same for 2 years and if a password hash will become in bad hands,
 * 			a hacker will in potential be able to crack a password in those 2 years.
 * 		 - Or should the user not be able to login and retrieve a new password via password forgotten.
 * 			After all: The password is expired, so you should not be able to use it anymore.
 * 			The only problem is, that it's not really user friendly. 
 * 		
 * 		 I prefer the second, but at the moment the first is implemented 
 */
function _password_expire_handle_expiry() {
  $now = time();

  $q_expire = db_update('password_expire')
    ->fields(array(
      'state' => PASSWORD_EXPIRED,
    ))
    ->condition('timestamp', $now, '<')
    ->execute();
}

/**
 * Trigger actions for new users who don't have a password expire entry yet
 * 
 */
function _password_expire_handle_newusers() {
  //Select all users which are not in password_expire table except anonymous user (ID 0)
  $q_newusers = db_query("SELECT u.uid FROM {users} u WHERE NOT EXISTS (SELECT p.uid FROM password_expire p WHERE p.uid = u.uid) AND u.uid != '0'")->fetchAll();

  //Calculate new expiry date and insert in password_expire table
  $now = time();
  $expire_period = strtotime(variable_get('password_expire_length'));
  $new_expire_period = $expire_period - $now;
  $new_expire_date = $now + $new_expire_period;

  foreach ($q_newusers as $key => $value) {		
    $q_insert_newusers = db_insert('password_expire')
      ->fields(array(
        'uid' => $value->uid,
        'timestamp' => $new_expire_date,
        'state' => PASSWORD_OK,
      ))
      ->execute();
  }
}

/**
 * Trigger some actions when a user enters a new password
 * 
 * @param int $uid, Unique ID of the user
 * @param string $pass, Password of the user
 */
function _password_expire_handle_new_password($uid, $pass) {
  //set new password
  $renew_password = _password_expire_renew_password($uid, $pass);

  switch($renew_password) {
    case FALSE:
      watchdog(basename(__FILE__), 'Unable to set password or expiry date for user ID: ' & $uid, NULL, WATCHDOG_ERROR, '');
      return FALSE;
      break;
      
    case PASSWORD_SAME:
      return PASSWORD_SAME;
      break;
      
    default:
      //set new password expiration date
      $renew_expiredate = _password_expire_renew_expirydate($uid);

      if ($renew_expiredate != FALSE) {
        //send e-mail to inform user that his password is changed
        _password_expire_mail_user($uid, TRUE);
      }
      return TRUE;
      break;
      
  }
}

/**
 * Function to renew an expired password
 * First the password will be hashed using drupal's hash function, then the password of the user will be updated 
 * 
 * @param int $uid, Unique ID of the user
 * @param string $pass, Password of the user
 */ 
function _password_expire_renew_password($uid, $pass) {
  //renew password, bootstrap is required for user_hash_password function
  require_once DRUPAL_ROOT . '/includes/bootstrap.inc';
  drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
  require_once DRUPAL_ROOT . '/includes/password.inc';

  if (!empty($uid) && !empty($pass)) {
    $user = user_load($uid);

    if (user_check_password(trim($pass),$user)) {
      //Same password
      return PASSWORD_SAME;
    } else {
      //New password
    }
    $pass_hashed = user_hash_password(trim($pass));

    $q_pass = db_update('users')
      ->fields(array('pass'=>$pass_hashed))
      ->condition('uid', $uid, '=')
      ->execute();

    return $q_pass;
  } else {
    return FALSE;
  }
}

/**
 * Renew a users password expiry date
 *
 * @param int $uid, Unique ID of the user
 */
function _password_expire_renew_expirydate($uid) {
  $now = time();
  $expire_period = strtotime(variable_get('password_expire_length'));

  if (!empty($expire_period)) {
    $new_expire_period = $expire_period - $now;
    $new_expire_date = $now + $new_expire_period;

    $q_expire = db_update('password_expire')
      ->fields(array(
        'timestamp' => $new_expire_date,
        'state' => PASSWORD_OK,
      ))
      ->condition('uid', $uid, '=')
      ->execute();

    if ($q_expire == 0) {
      $expired = db_query('SELECT p.uid FROM {password_expire} p WHERE p.uid = :uid', array(':uid' => $uid))->fetchAll();
      $expired_rowcount = db_query('SELECT p.uid FROM {password_expire} p WHERE p.uid = :uid', array(':uid' => $uid))->rowCount();

      if ($expired_rowcount <= 0) {
        //No password expiry entry available so insert new one
        $q_expire = db_insert('password_expire')
          ->fields(array(
            'uid' => $uid,
            'timestamp' => $new_expire_date,
            'state' => PASSWORD_OK,
          ))
          ->execute();
      }
    }
    return $q_expire;
  } else {
    return FALSE;
  }
}

/**
 * For security: Inform user that his password is changed
 * An e-mail will only be sent when the message is marked as active on the configuration page
 *
 * @param int $uid, Unique ID of the user
 * @param boolean $success, Whether the password has been changed successfully
 * @return $result or FALSE
 */
function _password_expire_mail_user($uid, $success = FALSE) {
  if (empty($uid)) {
    return FALSE;
  }

  //global $base_root;

  if (variable_get('password_expire_email_password_changed_active') == 1 && isset($uid) && $success == TRUE) {
    $module = basename(__FILE__, '.module');
    $key = 'passwordchanged';
    $user = user_load($uid);
    $mailfrom = variable_get('site_mail', '');
    $mailto = $user->mail;
    $language = language_default();
    $params = array();
    $send = FALSE;	//Need some customizations to the message before sending
    $message = drupal_mail($module, $key, $mailto, $language, $params, $mailfrom, $send);

    $message['subject'] = token_replace(t(variable_get('password_expire_email_password_changed_subject')), _password_expire_token_array());
    $message['body'] = array();
    $message['body'][] = token_replace(t(variable_get('password_expire_email_password_changed_body')), _password_expire_token_array());

    // Retrieve the responsible implementation for this message.
    $system = drupal_mail_system($module, $key);
    // Format the message body.
    $message = $system->format($message);
    // Send e-mail.
    $message['result'] = $system->mail($message);
    
  } 
  elseif (variable_get('password_expire_email_password_failed_active') == 1 && isset($uid) && $success == FALSE) {
    $module = basename(__FILE__, '.module');
    $key = 'passwordfailed';
    $user = user_load($uid);
    $mailfrom = variable_get('site_mail', '');
    $mailto = $user->mail;
    $language = language_default();
    $params = array();
    $send = FALSE;	//Need some customizations to the message before sending
    $message = drupal_mail($module, $key, $mailto, $language, $params, $mailfrom, $send);

    $message['subject'] = token_replace(t(variable_get('password_expire_email_password_failed_subject')), _password_expire_token_array());
    $message['body'] = array();
    $message['body'][] = token_replace(t(variable_get('password_expire_email_password_failed_body')), _password_expire_token_array());

    // Retrieve the responsible implementation for this message.
    $system = drupal_mail_system($module, $key);
    // Format the message body.
    $message = $system->format($message);
    // Send e-mail.
    $message['result'] = $system->mail($message);
  }

  if (isset($message['result'])) {
    return $message['result'];
  } else {
    return FALSE;
  }		
}

/**
 * Implements hook_user_update()
 *
 * To handle new passwords when a users updates his profile
 * 
 */
function password_expire_user_update(&$edit, $account, $category) {
  if (isset($_POST['pass']['pass1']) && isset($account->uid)) {
    _password_expire_handle_new_password($account->uid, $_POST['pass']['pass1']);
  }
}

/**
 * Implements hook_form_alter()
 * 
 * To hide the masquerade block (of module 'masquerade') when a password is expired,
 * else the user could masquerade as another user even if his/her password is expired.
 * 
 */
function password_expire_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  if(_password_expire_is_expired($user->uid) == PASSWORD_EXPIRED) {
    if (module_exists('masquerade') && user_is_logged_in()) {
      if(isset($form_id) && $form_id == 'masquerade_block_1') {
        $form['#access'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_FORMID_form()
 *
 * To handle new passwords when a users updates his profile
 * 
 * @return array $form
 */
function password_expire_new_password_form($form, &$form_state){
  $form = array();

  $form['new_password']['pass_confirm'] = array(
    '#type'=> 'password_confirm',
    '#required' => TRUE,
    '#tree' => FALSE,
    '#weight' => 1,
  );	
  $form['new_password']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('OK'),
    '#weight' => 2,
  );	
  return $form;
}

/**
 * Implements hook_FORMID_form_validate()
 *
 * To handle validation of new_password_form
 * 
 */
function password_expire_new_password_form_validate($form, &$form_state) {
  if (!isset($form_state['values']['pass_confirm'])) {
    form_set_error('new_password][pass_confirm', t('Please enter a password'));
  }

  if (isset($form['new_password']['pass_confirm']['#value']['pass1']) && isset($form['new_password']['pass_confirm']['#value']['pass2'])) {
    if ($form['new_password']['pass_confirm']['#value']['pass1'] != $form['new_password']['pass_confirm']['#value']['pass2']) {
      form_set_error('new_password][pass_confirm', t('Passwords are not equal'));
    }
  }
}

/**
 * Implements hook_FORMID_form_submit()
 *
 * To handle submit of new_password_form
 * 
 */
function password_expire_new_password_form_submit($form, &$form_state) {
  global $user;

  //set new password
  if ($form['new_password']['pass_confirm']['#value']['pass1'] == $form['new_password']['pass_confirm']['#value']['pass2']) {
    $renew_password = _password_expire_handle_new_password($user->uid, $form['new_password']['pass_confirm']['#value']['pass1']);
    if ($renew_password == TRUE) {
      $_GET['q'] = 'password/success';
    } 
    elseif ($renew_password == PASSWORD_SAME) {
      unset($_SESSION['messages']);	//Prevent displaying messages twice
      drupal_set_message('Please choose a different password then before.');
      $_GET['q'] = 'password/change';
    } else {
      $_GET['q'] = 'password/error';
    }
  }
}

/**
 * Function to display a message when the password is changed successfully
 * 
 * @return string $ret
 */
function _password_expire_password_success() {
  unset($_SESSION['messages']);	//Prevent displaying messages twice
  drupal_set_message('Your password has been changed successfully.');

  //page callback requires a string
  $msg = '';
  return $msg;
}

/**
 * Function to display a message when the password could not be set
 * 
 * @return string $ret
 */
function _password_expire_password_error() {
  unset($_SESSION['messages']);	//Prevent displaying messages twice
  drupal_set_message('Unable to set password, please contact your site administrator.');

  //page callback requires a string
  $msg = '';
  return $msg;
}

/**
 * Function to detect whether a page is an overlay-page or not
 * 
 * @return boolean TRUE: page is an overlay, FALSE: page is not an overlay
 */
function _password_expire_page_is_overlayed() {
  if (isset($_SERVER['REDIRECT_QUERY_STRING']) && preg_match('/render=overlay$/', $_SERVER['REDIRECT_QUERY_STRING']) == TRUE) {
    return TRUE;
  } else {
    return FALSE;
  }
}
